import {Geist, Geist_Mono} from "next/font/google";
import {ApiProvider} from "@/context/ApiProvider";
import "@/style/globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * 루트 레이아웃 컴포넌트
 *
 * 이 컴포넌트는 애플리케이션의 전체적인 레이아웃을 정의합니다.
 * 폰트를 설정하고, 자식 컴포넌트를 렌더링합니다.
 *
 * @param {object} props - 컴포넌트에 전달되는 props
 * @param {React.ReactNode} props.children - 내부에 렌더링될 자식 요소
 * @returns {JSX.Element} 루트 레이아웃의 JSX
 */
export default function RootLayout({children}) {
    return (
        <html lang="ko">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/* ✅ 모든 페이지를 ApiProvider로 감쌈 */}
        <ApiProvider>
            {children}
        </ApiProvider>
        </body>
        </html>
    );
}
